services:
  - type: web
    name: retail-ai-decision-demo
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run app.py --server.address 0.0.0.0 --server.port $PORT
    autoDeploy: true
